#!/usr/bin/env python

import sys
import cooperhewitt.unicode.names as names

if __name__ == '__main__':

    input = sys.argv[1:]
    input = " ".join(input)

    input = input.decode('utf-8')

    ref = names.lookup()

    for char in input:
        print ref.name(char)
